#!/bin/sh
# /etc/init.d/helloKeyboard

case "$1" in
  start)
    echo "Loading helloKeyboard module..."
    /sbin/modprobe helloKeyboard
    ;;
  stop)
    echo "Unloading helloKeyboard module..."
    /sbin/modprobe -r helloKeyboard
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
